# Generated by Django 5.2.10 on 2026-01-19 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_category_post_alter_category_name_jobpost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='jobs.category'),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='jobs.tag'),
        ),
    ]
